### ISSUE TITLE
Holmer fillarm not working since update of holmer pack

### ISSUE THREAD

**Issue by Evilman2517** [stijnwop/manureSystem#121] opened 2020-09-13 00:05 UTC
Hello,

I noticed that the fillarm of the Holmer 435 of the holmer pack stopped working (SP / MP) with the latest update (1.0.2.0 25.06.20). I guess Giants edited something that now interferes with the additions the manureSystem do.

**Comment by MBTrac366** [comment] 2020-09-16 22:01
Hi, I can confirm this issue. Tested in SP, the Holmer 435 doesn't give me the option to activate the pump using the fillarm (the TV585 works fine). Took some screens to show and added my log file, maybe this can help finding the issue. 
[log.txt](https://github.com/stijnwop/manureSystem/files/5235152/log.txt)


![fsScreen_2020_09_16_23_42_37](https://user-images.githubusercontent.com/71411042/93396621-43792c00-f878-11ea-9b93-694017646955.png)
![fsScreen_2020_09_16_23_44_50](https://user-images.githubusercontent.com/71411042/93396627-46741c80-f878-11ea-9e88-cdb925b14a7c.png)
![fsScreen_2020_09_16_23_47_19](https://user-images.githubusercontent.com/71411042/93396633-496f0d00-f878-11ea-9c35-b6574db5d2ae.png)
![fsScreen_2020_09_16_23_47_34](https://user-images.githubusercontent.com/71411042/93396678-5a1f8300-f878-11ea-9e56-5156f8a4652c.png)
![fsScreen_2020_09_16_23_48_32](https://user-images.githubusercontent.com/71411042/93396688-5d1a7380-f878-11ea-8a9f-6881311dc54e.png)
![fsScreen_2020_09_16_23_49_33](https://user-images.githubusercontent.com/71411042/93396694-60156400-f878-11ea-9c54-baabc987b487.png)
![fsScreen_2020_09_16_23_49_59](https://user-images.githubusercontent.com/71411042/93396702-61df2780-f878-11ea-870b-9026ab54ed7a.png)

**Comment by Wolfi-123** [comment] 2021-01-11 18:23
Hi guys,

I still have the issue with the 435 not working and the 585 working.... 

Has somebody figured out a way to fix this?

**Comment by MBTrac366** [comment] 2021-01-11 18:59
Sadly, no

**Comment by stijnwop** [comment] 2021-01-11 19:22
Seems to be some missing variable with the 435, which needs some investigation.

Will try to look at it this weekend.

**Comment by MBTrac366** [comment] 2021-01-11 19:23
Nice, thanks in advance

**Comment by stijnwop** [comment] 2021-01-23 15:34
Should be fixed.

**Closed** 2021-07-09 19:30 UTC
Labels: bug, fixed
