### ISSUE TITLE
Holmer DLS

### ISSUE THREAD

**Issue by kapatyh** [stijnwop/manureSystem#26] opened 2020-03-15 08:30 UTC
I can 't connect the hose to the Holmer DLS.. some players can , and some can 't ... I started the game without mods.

**Comment by stijnwop** [comment] 2020-03-15 08:33
Duplicate of #13 ..
You are running the steam version.

Please update with the latest GitHub source, issue has been fixed

**Comment by kapatyh** [comment] 2020-03-15 08:43
> Дубликат [№13 ](https://github.com/stijnwop/manureSystem/issues/13)..
> Вы работаете в версии steam.
> 
> Пожалуйста, обновите с последним источником GitHub, проблема была исправлена

I got lost on the site , and where can I download the updated product ?

**Comment by stijnwop** [comment] 2020-03-15 18:50
There's a big green button with DOWNLOAD on it.

Rezip the source you got from that (DONT just drop it in your modfolder) and name it `FS19_manureSystem`

Thats for the future.. for the time being I attached the latest source.

[FS19_manureSystem.zip](https://github.com/stijnwop/manureSystem/files/4334856/FS19_manureSystem.zip)

**Closed by stijnwop** 2020-03-15 18:50 UTC
